packages:
  - "packages/core"
  - "packages/benchmark"
  - "packages/playground/*"

catalog:
  hash-wasm: "^4.12.0"
  ts-node: "^10.9.2"
  vue: "^3.5.13"
  "@vitejs/plugin-vue": "^5.2.3"
  vite: "^6.3.2"
  react: "^18.2.0"
  react-dom: "^18.2.0"
  "@babel/core": "^7.26.0"
  "@babel/preset-env": "^7.26.0"
  "@babel/preset-react": "^7.26.3"
  "@babel/preset-typescript": "^7.26.0"
  "@types/react": "^18.2.0"
  "@types/react-dom": "^18.2.0"
  babel-loader: "^9.2.1"
  webpack: "^5.97.1"
  webpack-cli: "^6.0.1"
  webpack-dev-server: "^5.2.0"
  typescript: "^5.8.3"
  tsup: "^8.4.0"
  rimraf: "^6.0.1"
